# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iDriverTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iDriverTest

  target 'iDriverTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iDriverTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'iDriverTest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iDriverTest-tvOS

  target 'iDriverTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
